# .github/workflows/update_resume.yml
name: Update Resume

on:
  schedule:
    - cron: "50 23 * * *" # KST 기준 오전 8:50 (UTC 23:50)
    - cron: "50 3 * * *" # KST 기준 오후 12:50 (UTC 3:50)
    # - cron: "0 9 * * *" # KST 기준 오후 6:00 (UTC 09:00)
  workflow_dispatch: # 수동 실행을 위해 추가

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build project
        run: pnpm tsc

      - name: Run update script
        env:
          JOBKOREA_ID: ${{ secrets.JOBKOREA_ID }}
          JOBKOREA_PWD: ${{ secrets.JOBKOREA_PWD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DEBUG: pw:api # Playwright 디버그 로그 활성화
        run: node dist/index.js

      # - name: Upload Playwright Artifacts on Failure
      #   if: failure()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: playwright-artifacts
      #     path: |
      #       error-*.png
      #       videos/
      #       trace.zip
      #       playwright.log
