# .github/workflows/update_resume.yml
name: Update Resume

on:
  schedule:
    - cron: "50 23 * * *" # KST 기준 오전 8:50 (UTC 23:50)
    - cron: "50 3 * * *" # KST 기준 오후 12:50 (UTC 3:50)
  workflow_dispatch: # 수동 실행을 위해 추가

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm tsc

      - name: Run update script
        env:
          JOBKOREA_ID: ${{ secrets.JOBKOREA_ID }}
          JOBKOREA_PWD: ${{ secrets.JOBKOREA_PWD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node dist/index.js
